[package]
name = "plotlars"
version = "0.5.0"
authors = ["Alberto Cebada Aleu <contact@albertocebada.com>"]
edition = "2021"
rust-version = "1.80.1"
description = "Plotlars is a Rust library designed to facilitate the integration between the Polars data analysis library and visualization libraries."
documentation = "https://docs.rs/plotlars/latest/plotlars/"
readme = "README.md"
homepage = "https://github.com/alceal/plotlars"
repository = "https://github.com/alceal/plotlars"
license = "MIT"
keywords = ["chart", "plot", "plotly", "polars", "visualization"]
categories = ["visualization"]

[dependencies]
bon = "2.3.0"
plotly = "0.10.0"
polars = { version = "0.43.1", features = [
    "dtype-categorical",
    "lazy",
    "strings",
] }
serde = "1.0.210"
